Repository LudovicoPiero/dotfiles, pull requests merged in 2023-12, with the labels that each got.

#218 chore(flake/spicetify-nix): `c9b1d9bd` -> `f6c7b0f6`
  flake.lock
Labels: automated, uwu

#219 chore(flake/unstable): `e2fa3d60` -> `3934dbde`
  flake.lock
Labels: automated, uwu

#212 chore(flake/master): `3f83e9f1` -> `54c8a156`
  flake.lock
Labels: automated, uwu

#217 chore(flake/nh): `4298c924` -> `c192a4a9`
  flake.lock
Labels: automated, uwu

#223 chore(flake/chaotic): `45d2aa68` -> `72d65d0d`
  flake.lock
Labels: automated, uwu

#222 chore(flake/master): `54c8a156` -> `d491c9db`
  flake.lock
Labels: automated, uwu

#221 chore(flake/flake-parts): `8c9fa254` -> `34fed993`
  flake.lock
Labels: automated, uwu

#233 chore(flake/spicetify-nix): `58f597db` -> `afe1e6b2`
  flake.lock
Labels: automated, uwu

#251 chore(flake/unstable): `3771eeac` -> `0b62f5ad`
  flake.lock
Labels: automated, uwu

#241 chore(flake/hyprland): `99ca26d4` -> `68783d90`
  flake.lock
Labels: automated, uwu

#263 chore(flake/devshell): `c3bd7791` -> `44ddedcb`
  flake.lock
Labels: automated, uwu

#265 chore(flake/chaotic): `bd466e00` -> `5a9ea054`
  flake.lock
Labels: automated, uwu

#264 chore(flake/hyprland): `3bb9c7c5` -> `8bd86cf3`
  flake.lock
Labels: automated, uwu

#271 chore(flake/unstable): `d08f6384` -> `9ed8ade7`
  flake.lock
Labels: automated, uwu

#273 chore(flake/nix-super): `cb968c09` -> `661b025c`
  flake.lock
Labels: automated, uwu

#283 chore(flake/nur): `34c38401` -> `d854884a`
  flake.lock
Labels: automated, uwu

#282 chore(flake/hyprland): `a794eecd` -> `11d1c504`
  flake.lock
Labels: automated, uwu

#285 chore(flake/nur): `d854884a` -> `eeb0b84c`
  flake.lock
Labels: automated, uwu

#289 chore(flake/spicetify-nix): `79d06a59` -> `52fa6b83`
  flake.lock
Labels: automated, uwu

#290 chore(flake/nixpkgs): `17572dd7` -> `82787a00`
  flake.lock
Labels: automated, uwu

#287 chore(flake/hyprland): `11d1c504` -> `af6aae4e`
  flake.lock
Labels: automated, uwu

#286 chore(flake/home-manager): `ac721691` -> `e6b7303b`
  flake.lock
Labels: automated, uwu

#292 chore(flake/hyprland): `0c10b8ab` -> `167f2ed3`
  flake.lock
Labels: automated, uwu

#291 chore(flake/chaotic): `d16bc3c5` -> `fcb86262`
  flake.lock
Labels: automated, uwu

#294 chore(flake/nur): `e45022e0` -> `46e1aa64`
  flake.lock
Labels: automated, uwu

#299 chore(flake/spicetify-nix): `41edd889` -> `6fd5db51`
  flake.lock
Labels: automated, uwu

#295 chore(flake/chaotic): `29cd0da2` -> `7369da9b`
  flake.lock
Labels: automated, uwu

#302 chore(flake/nixpkgs): `120a26f8` -> `224b3a5a`
  flake.lock
Labels: automated, uwu

#304 chore(flake/nur): `cf183d15` -> `8cf518b0`
  flake.lock
Labels: automated, uwu

#311 chore(flake/nixpkgs): `224b3a5a` -> `02357add`
  flake.lock
Labels: automated, uwu

#305 chore(flake/chaotic): `ea53eaf3` -> `5425e55c`
  flake.lock
Labels: automated, uwu

#310 chore(flake/hyprland): `f7cde9c9` -> `b1b8d732`
  flake.lock
Labels: automated, uwu

#309 chore(flake/nur): `8cf518b0` -> `1d374446`
  flake.lock
Labels: automated, uwu

#314 chore(flake/nixpkgs): `02357add` -> `7d692982`
  flake.lock
Labels: automated, uwu

#308 chore(flake/home-manager): `0e2e443f` -> `e9b9ecef`
  flake.lock
Labels: automated, uwu

#316 chore(flake/nur): `1d374446` -> `784c8293`
  flake.lock
Labels: automated, uwu

#318 chore(flake/nixpkgs): `7d692982` -> `3a16c644`
  flake.lock
Labels: automated, uwu

#319 chore(flake/nur): `784c8293` -> `a986d4b1`
  flake.lock
Labels: automated, uwu

#313 chore(flake/chaotic): `479bf876` -> `3662460d`
  flake.lock
Labels: automated, uwu

#320 chore(flake/hyprland): `b1b8d732` -> `ef445093`
  flake.lock
Labels: automated, uwu

#323 chore(flake/nur): `a986d4b1` -> `d63d8a56`
  flake.lock
Labels: automated, uwu

#326 chore(flake/nixpkgs): `3a16c644` -> `fa5e0f2e`
  flake.lock
Labels: automated, uwu

#327 chore(flake/chaotic): `3662460d` -> `d496c55f`
  flake.lock
Labels: automated, uwu

#307 chore(flake/spicetify-nix): `11016e63` -> `914a0262`
  flake.lock
Labels: automated, uwu

#321 chore(flake/impermanence): `0f317c2e` -> `123e9420`
  flake.lock
Labels: automated, uwu

#317 chore(flake/nix-index-database): `45d82e0a` -> `4605ccd7`
  flake.lock
Labels: automated, uwu

#306 chore(flake/base16-schemes): `a9112eaa` -> `2b6f2d06`
  flake.lock
Labels: automated, uwu

#324 chore(flake/hyprland): `ef445093` -> `d9b74ff9`
  flake.lock
Labels: automated, uwu

#332 chore(flake/treefmt-nix): `d06b70e5` -> `29613752`
  flake.lock
Labels: automated, uwu

#330 chore(flake/home-manager): `e9b9ecef` -> `efc177c1`
  flake.lock
Labels: automated, uwu

#331 chore(flake/nh): `bd225f25` -> `37b0d469`
  flake.lock
Labels: automated, uwu

#328 chore(flake/spicetify-nix): `914a0262` -> `26ad54b4`
  flake.lock
Labels: automated, uwu

#329 chore(flake/nur): `d63d8a56` -> `cc008520`
  flake.lock
Labels: automated, uwu

#334 chore(flake/nur): `cc008520` -> `eef232c5`
  flake.lock
Labels: automated, uwu

#361 refactor editor
  home-configurations/airi.nix
  home-modules/default.nix
  home-modules/editor/emacs/README.org
  home-modules/editor/emacs/default.nix
  home-modules/editor/emacs/modules/emacs-init-defaults.nix
  home-modules/editor/emacs/modules/emacs-init.nix
  home-modules/editor/emacs/prelude.el
  home-modules/editor/emacs/snippets/nix-mode/cargoHash
  home-modules/editor/emacs/snippets/nix-mode/cargoSha256
  home-modules/editor/emacs/snippets/nix-mode/home-manager.users
  home-modules/editor/emacs/snippets/nix-mode/meta
  home-modules/editor/emacs/snippets/nix-mode/modSha256
  home-modules/editor/emacs/snippets/nix-mode/sha256
  home-modules/editor/nvim/README.md
  home-modules/editor/nvim/default.nix
  home-modules/editor/nvim/init.lua
  home-modules/editor/nvim/lua/custom/plugins/bufferline.lua
  home-modules/editor/nvim/lua/custom/plugins/neo-tree.lua
Labels: enhancement

#367 chore(flake/chaotic): `69a7b82c` -> `778e166a`
  flake.lock
Labels: automated, uwu

#363 chore(flake/spicetify-nix): `ba6e4b47` -> `d163d7d0`
  flake.lock
Labels: automated, uwu

#364 chore(flake/nur): `46403c0c` -> `cf0ae650`
  flake.lock
Labels: automated, uwu

#365 chore(flake/hyprland): `f013acc6` -> `b25b0643`
  flake.lock
Labels: automated, uwu

#373 chore(flake/home-manager): `16fcb967` -> `80679ea5`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#375 chore(flake/nur): `cf0ae650` -> `19c254d7`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#374 chore(flake/hyprland): `b25b0643` -> `4f99e805`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#377 chore(flake/lanzaboote): `9186a778` -> `47032189`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#378 chore(flake/nur): `19c254d7` -> `59425032`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#380 chore(flake/emacs-overlay): `1c1dd489` -> `9147a422`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#381 chore(flake/impermanence): `123e9420` -> `3d599bd6`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#383 chore(flake/nur): `59425032` -> `76bf3c9f`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#382 chore(flake/hyprland): `4f99e805` -> `2c2ff4b6`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#379 chore(flake/chaotic): `778e166a` -> `1da8a8ce`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#384 chore(flake/chaotic): `1da8a8ce` -> `80d0d925`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#386 chore(flake/hyprland): `2c2ff4b6` -> `191fa587`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#387 chore(flake/emacs-overlay): `9147a422` -> `cf14f3f6`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#385 chore(flake/nur): `76bf3c9f` -> `a17e7841`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#391 chore(flake/impermanence): `3d599bd6` -> `033643a4`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#394 chore(flake/spicetify-nix): `d163d7d0` -> `cbdb2d1a`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#392 chore(flake/hyprland): `191fa587` -> `6cd82d94`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#389 chore(flake/emacs-overlay): `cf14f3f6` -> `995ac3a4`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#388 chore(flake/nur): `a17e7841` -> `8d246efc`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#393 chore(flake/home-manager): `80679ea5` -> `45854459`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#390 chore(flake/lanzaboote): `47032189` -> `f707a9be`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#395 chore(flake/chaotic): `80d0d925` -> `40bd292c`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#397 chore(flake/nur): `8d246efc` -> `eacde6f9`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#396 chore(flake/emacs-overlay): `995ac3a4` -> `d72b6439`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#399 chore(flake/lanzaboote): `f707a9be` -> `7229dd85`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#398 chore(flake/nur): `eacde6f9` -> `de9b2c75`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#400 Nvfetcher update
  pkgs/_sources/generated.json
  pkgs/_sources/generated.nix
  pkgs/_sources/wezterm-ff2743748c238e5cdd6e7cb4ed19517d08dd511f/Cargo.lock
Labels: automated, uwu, keep-up-to-date

#403 chore(flake/nur): `de9b2c75` -> `c5559571`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#402 chore(flake/home-manager): `45854459` -> `77c698fa`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#404 chore(flake/chaotic): `40bd292c` -> `028a52d8`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#405 chore(flake/emacs-overlay): `d72b6439` -> `a405e8be`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#401 chore(flake/spicetify-nix): `cbdb2d1a` -> `df301563`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#406 Nvfetcher update
  pkgs/_sources/generated.json
  pkgs/_sources/generated.nix
Labels: automated, uwu, keep-up-to-date

#410 chore(flake/nur): `c5559571` -> `4a8f8f53`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#409 chore(flake/chaotic): `028a52d8` -> `5d7c4dc2`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#408 chore(flake/emacs-overlay): `a405e8be` -> `e9e995a2`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#411 chore(flake/spicetify-nix): `df301563` -> `97bf8b7c`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#407 chore(flake/home-manager): `77c698fa` -> `2aff324c`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#414 chore(flake/emacs-overlay): `e9e995a2` -> `dbf41b39`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#415 chore(flake/spicetify-nix): `97bf8b7c` -> `30100476`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#412 chore(flake/chaotic): `5d7c4dc2` -> `f2d920f8`
  flake.lock
Labels: automated, uwu, keep-up-to-date

#417 Nvfetcher update
  pkgs/_sources/generated.json
  pkgs/_sources/generated.nix
Labels: automated, uwu, keep-up-to-date
