Repository LudovicoPiero/dotfiles, pull requests merged in 2025-03, with the labels that each got.

#929 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#930 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#931 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#937 Package Update
  packages/_sources/generated.json
  packages/_sources/generated.nix
Labels: automated, uwu, keep-up-to-date

#938 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#939 Package Update
  packages/_sources/generated.json
  packages/_sources/generated.nix
Labels: automated, uwu, keep-up-to-date

#941 Package Update for iosevka-q
  packages/iosevka-q/default.nix
Labels: automated, uwu, keep-up-to-date

#940 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#943 WIP
  .github/mergify.yml
Labels: WIP

#945 Nvfetcher Source Update
  packages/_sources/generated.json
  packages/_sources/generated.nix
  packages/_sources/wezterm-7053748e4d899e7fc5e202d6f903b052fc78e759/Cargo.lock
Labels: automated, uwu, keep-up-to-date

#946 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#950 treewide: don't use import
  modules/firefox/bookmarks.nix
  modules/firefox/default.nix
  modules/firefox/extensions.nix
  modules/firefox/search.nix
  modules/firefox/settings.nix
  modules/fish/default.nix
  modules/fish/functions.nix
  modules/fish/plugins.nix
  modules/fish/shellAliases.nix
  modules/floorp/bookmarks.nix
  modules/floorp/default.nix
  modules/floorp/extensions.nix
  modules/floorp/search.nix
  modules/floorp/settings.nix
  modules/hyprland/default.nix
  modules/hyprland/settings.nix
  modules/mako/default.nix
  modules/shared/default.nix
  modules/shared/home-manager.nix
  modules/waybar/default.nix
  modules/waybar/style.nix
  modules/zsh/default.nix
  modules/zsh/initExtra.nix
  modules/zsh/shellAliases.nix
Labels: CI:fail
