Repository LudovicoPiero/dotfiles, pull requests merged in 2025-05, with the labels that each got.

#978 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#980 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#982 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#984 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#985 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#986 Automated package updates
  packages/_sources/generated.json
  packages/_sources/generated.nix
Labels: automated, uwu, keep-up-to-date

#991 modules: add zen-browser
  flake.lock
  flake.nix
  hosts/allOptions/myOptions.nix
  hosts/sforza/myOptions.nix
  modules/default.nix
  modules/zen-browser/README.md
  modules/zen-browser/bookmarks.nix
  modules/zen-browser/default.nix
  modules/zen-browser/extensions.nix
  modules/zen-browser/search.nix
  modules/zen-browser/settings.nix
Labels: WIP

#992 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#993 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date

#995 Update flake.lock
  flake.lock
Labels: automated, keep-up-to-date
